### ISSUE TITLE
[Feature Request] Discord Roles Sync to Forum

### ISSUE THREAD

**Issue by evonix** [opt-natter/discord-mybb-sync#11]
Hey there!
This Plugin looks promising! I wanna use this Plugin to sync my roles to the forum. For example: I got several roles in Discord and if i add someone in it in Discord i want them in the Group on the Forum. Is this possible to do?

Regard,
Evonix

**Comment by opt-natter** [comment]
Unfortunately it is not possible with this plugin and is not planned to be added.
