### ISSUE TITLE
Instruction on what to configure?

### ISSUE THREAD

**Issue by SypherRed** [opt-natter/discord-mybb-sync#16]
Yeah hey there...

I'm really curious what should be edited in the groups.
Besides that, I still don't understand how the Custom Profile Field should be added.

I would really be thankful for someone that could at least explain it bit more than just

"Open the Settings Tab and configure your groups"

**Comment by opt-natter** [comment]
https://github.com/opt-natter/discord-mybb-sync/blob/master/README.md was updated,
