### ISSUE TITLE
No Role Sync

### ISSUE THREAD

**Issue by Rafiki47** [opt-natter/discord-mybb-sync#17]
Hello, 
I only installed MyBB because of this plugin, so I hope you can help me. 

The configuration works great, in "Discord Right Sync Settings" all discord roles are shown in the selection. 

Now I have added the correct DiscordName#1234 in "Location" in my test account. 

Unfortunately nothing happens. On the discord no role of the two configured test roles was distributed.

**Comment by familypet** [comment]
I have the exact same problem. Did you ever find a fix for this? @Rafiki47 @opt-natter

**Comment by TerranUlm** [comment]
I've figured how to fix it: https://github.com/opt-natter/discord-mybb-sync/issues/20
