### ISSUE TITLE
Not all roles synced. Discord API limit reached.

### ISSUE THREAD

**Issue by familypet** [opt-natter/discord-mybb-sync#19]
I am getting the error:  'Not all roles synced. Discord API limit reached.' when I am manually running the task ONCE on only one test account, however I am getting rate limited already?

**Comment by DonoDayZ** [comment]
same

**Comment by TerranUlm** [comment]
There has been some API changes since the last update to this code...

**Comment by TerranUlm** [comment]
I've figured how to fix it: https://github.com/opt-natter/discord-mybb-sync/issues/20

**Comment by opt-natter** [comment]
Thanks Terran
