### ISSUE TITLE
SQL Error on MyBB

### ISSUE THREAD

**Issue by Luke-99870** [opt-natter/discord-mybb-sync#2]
Hi, do you know how to fix this? I installed the plugin and put in my guide id and bot token, then went to click on it to configure groups and was met with this:

`nscode`='select\n0=none\n424669065504882698=@everyone\n431769811597393941=Mafia Network's DarkRP\n431768826607042560=Oxyl\n431766919067074560=Logger\n429987590230245376=Stormtroopers\n429987707196801034=Shadow Troopers\n429987707285012480=Shock Troopers\n429987718223626251=Engineers\n429987718987120650=TIE Pilots\n429987719263813643=501st Legion\n429987720300068864=Shore Troopers\n429987720899854337=ISB\n429987721847504906=Death Troopers\n429988216498683904=Army High Command\n429988223176015892=Navy High Command\n430330449605165067=Sith\n429927885629947914=Bronze VIP\n429927987333300234=Silver VIP\n429928351122194452=Gold VIP\n429927474797871114=Trial Mod\n429927337698525194=Moderator\n429927232199196672=Administrator\n429927089899307008=Super Administrator\n429926486103818242=Head Administrator\n429926835359449089=Community Manager\n429926304956022814=Co-Owner\n429915490371239949=Owner\n431564809947840513=BOT' WHERE name LIKE 'drs_setting_gid%' AND gid='33'`

**Comment by opt-natter** [comment]
What version of Mybb are you using?

**Comment by Luke-99870** [comment]
The Latest One - 1.8.15

**Comment by opt-natter** [comment]
The cause was your Role name. 

It should now be fixed. Please replace discord_right_sync.php with the current version and test again.
