### ISSUE TITLE
tasks not being run automatically

### ISSUE THREAD

**Issue by familypet** [opt-natter/discord-mybb-sync#21]
Tasks can only be ran manually. scheduled tasks don't work, nothing shows in logs

**Comment by opt-natter** [comment]
Is the task configured and enabled?
Do you have enough page hits to be able to run the task in time? Maybe MyBB priorities other tasks. Check the "Next Run" Time under Admin-CP -> Tools & Maintenance -> Task Manager
![tasks](https://user-images.githubusercontent.com/18631648/127204250-2c5b88d8-75ce-4085-bec1-67cda8bf7975.jpg)

**Comment by familypet** [comment]
everything is setup to how it is in your screenshot, I've also created another task that runs every minute as a test, neither work. 
what do you mean by having enough page hits though?

**Comment by familypet** [comment]
Had to set it up as a cronjob for it to work, thanks!
