### ISSUE TITLE
Having trouble getting it working.

### ISSUE THREAD

**Issue by fundafecktals** [opt-natter/discord-mybb-sync#22]
Will having emojis in the discord role affect it syncing the users on the forum?

Edit: Just made it so one role will only sync

Edit 2: Getting this error 
Warning - [2] 'htmlspecialchars() expects parameter 1 to be string, array given' - Line: 601 - File: inc/plugins/discord_right_sync.php

**Comment by fundafecktals** [comment]
Also, getting this problem in the task log

<html>
<body>


Warning - [2] 'htmlspecialchars() expects parameter 1 to be string, array given' - Line: 601 - File: inc/plugins/discord_right_sync.php
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by fundafecktals** [comment]
I removed the emoji and now get this in the task log. 

discord_right_sync returned false

**Comment by fundafecktals** [comment]
Still getting the same error 

Warning - [2] 'htmlspecialchars() expects parameter 1 to be string, array given' - Line: 601 - File: inc/plugins/discord_right_sync.php

**Comment by fundafecktals** [comment]
Just made it so one role will only sync

**Comment by opt-natter** [comment]
It was not tested with emojis. 

Line: 601 ist just an debug output. You can delete this line to remove the Warning.
