### ISSUE TITLE
Wont set roles

### ISSUE THREAD

**Issue by Enclusion** [opt-natter/discord-mybb-sync#3]
I installed following settings. I set up the config. Now every 5 minutes no role is set. Any idea? Everything installed.

**Comment by opt-natter** [comment]
Any error message in your log files?
Have you provided your discord Bot with the rights to change roles?
Does mybb run you tasks?

**Comment by SirDabs** [comment]
Hey im having this same issue what can i do to solve it how do i see if mybb is running my tasks?

**Comment by robbie6** [comment]
I too am having that same issue only with mine it gets putting my members back to everyone role and removing all other roles please help me someone. Everything is setup.

**Comment by opt-natter** [comment]
Check you Admin-CP -> Tools & Maintenance -> Task Manager

There you can manuelly run the task for testing and also see the Logs.
