### ISSUE TITLE
Call to undefined function

### ISSUE THREAD

**Issue by hcphoon01** [opt-natter/discord-mybb-sync#4]
When trying to edit the plugin settings I get this error
`Fatal error: Uncaught Error: Call to undefined function Unirest\curl_init() in /var/www/forums/inc/plugins/Unirest/Unirest/Request.php:396 Stack trace: #0 /var/www/forums/inc/plugins/Unirest/Unirest/Request.php(236): Unirest\Request::send('GET', 'https://discord...', NULL, Array, NULL, NULL) #1 /var/www/forums/inc/plugins/discord_right_sync.php(388): Unirest\Request::get('https://discord...', Array) #2 /var/www/forums/inc/plugins/discord_right_sync.php(346): discord_right_sync_get_querry_discord('guilds/44054566...') #3 /var/www/forums/inc/class_plugins.php(142): discord_right_sync_settings_update('') #4 /var/www/forums/admin/modules/config/settings.php(875): pluginSystem->run_hooks(Array) #5 /var/www/forums/admin/index.php(821): require('/var/www/forums...') #6 {main} thrown in /var/www/forums/inc/plugins/Unirest/Unirest/Request.php on line 396`

**Comment by opt-natter** [comment]
curl is required by this plugin. Please enable it or ask your Host.
