### ISSUE TITLE
Unirest issue

### ISSUE THREAD

**Issue by itzaidan** [opt-natter/discord-mybb-sync#5]
I don't know if i'm not doing it right but I followed the instructions to installing Unirest in the /inc/plugins/Unirest but idk if you have to only do the src folder which I've tried.

But it still says Unirest is required by Discord Right Sync.

Anyway i'm doing this wrong?

**Comment by MitchellPT** [comment]
Same!

**Comment by opt-natter** [comment]
The Structure should look as follows:
![unirest](https://user-images.githubusercontent.com/18631648/40378935-29d1bf76-5df5-11e8-9a52-0c8bd32efb2b.gif)

**Comment by itzaidan** [comment]
@opt-natter Worked. Thank you.
