### ISSUE TITLE
Work for only first few minutes then doesn't work

### ISSUE THREAD

**Issue by online0227** [opt-natter/discord-mybb-sync#9]
Work for only first few minutes then doesn't work. 
Idk why exactly but it looks like it's a problem somewhat related to token keep changing, maybe?

Also it doesn't look like setting roles for people who are offline.

**Comment by online0227** [comment]
sorry actuqlly it seems it works but takes way too much times to sync, like 30min when there is only 20people in discord. is there a way to boost its syncing speed?

**Comment by opt-natter** [comment]
You can increase the ammount the task in mybb is run. 
Your mybb board needs a higher ammount of page visits to be able to proces the syncronisation. Setup an cronjob which is calling you page once a minute.
